spring.application.name=SportradarTask

#MySQL config
spring.datasource.url=jdbc:mysql://localhost:5432/CopySpringDB
spring.datasource.username=root
spring.datasource.password=root


#SQL config
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false